[[repos]]
repo = "local"
hooks = [
    { id = "buf lint", name = "Buf Lint", language = "system", entry = "buf lint .", pass_filenames = false, fail_fast = true },
    { id = "buf breaking", name = "Buf Breaking Change Detection", language = "system", entry = "buf breaking . --against .git#branch=main", pass_filenames = false, fail_fast = true },
]
